# Generated by Django 6.0.1 on 2026-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_update_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInProgress',
            fields=[
            ],
            options={
                'verbose_name': 'В роботі',
                'verbose_name_plural': 'В роботі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.leadsubmission',),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('no_answer', 'Недозвон'), ('call_back', 'Перетелефонувати'), ('thinking', 'Обдумує'), ('push', 'Дотиснути'), ('waiting_payment', 'Очікуємо оплату'), ('data_collection', 'Збір Даних'), ('in_process', 'В процессі'), ('closed', 'Закритий'), ('offer_new', 'Запропонувати нові послуги')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_buy_text',
            field=models.CharField(default='Отримати безкоштовну консультацію', max_length=60, verbose_name='Кнопка «Купити»'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_sell_text',
            field=models.CharField(default='Дізнатися вартість моєї землі', max_length=60, verbose_name='Кнопка «Продати»'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(default='Повний юридичний супровід, пошук покупців та оцінка вартості. Працюємо з усіми типами землі.', verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='Допоможемо швидко та вигідно продати земельну ділянку чи пай в Україні', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='title',
            field=models.CharField(default='Які земельні ділянки ми допомагаємо продати?', max_length=120, verbose_name='Заголовок секції'),
        ),
    ]
